### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by aswede** [ChrisRichner/ARGUS-TV-GuideEnhancer#22]
I am struggling getting GuideEnricher to work after installing the most recent version. It will not startup; there seems to be a fatal error right away, which leads me to beleive I am doing something wrong or am missing something obvious. Can you please give me some ideas where to start looking?

Thanks.

Log file:
2015-06-26 09:24:04 [5] INFO  GuideEnricher.Service - Starting
2015-06-26 09:24:04 [7] INFO  GuideEnricher.Service - Connection and event listener task started...
2015-06-26 09:24:15 [11] INFO  GuideEnricher.Service - SubscribeServiceEvents() succeeded
2015-06-26 09:24:19 [5] DEBUG GuideEnricher.tvdb.TvdbLibAccess - Language: de
2015-06-26 09:24:21 [5] ERROR GuideEnricher.Service - Error enriching
System.AggregateException: One or more errors occurred. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: input
   at System.Text.RegularExpressions.Regex.IsMatch(String input)
   at GuideEnricher.Enricher.<AddUpcomingProgramsAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GuideEnricher.Enricher.<EnrichUpcomingProgramsAsync>d__8.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at GuideEnricher.Service.Enrich(Object state, ElapsedEventArgs eventArgs)
---> (Inner Exception #0) System.ArgumentNullException: Value cannot be null.
Parameter name: input
   at System.Text.RegularExpressions.Regex.IsMatch(String input)
   at GuideEnricher.Enricher.<AddUpcomingProgramsAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GuideEnricher.Enricher.<EnrichUpcomingProgramsAsync>d__8.MoveNext()<---

2015-06-26 09:26:20 [4] INFO  GuideEnricher.Service - Service stopping
2015-06-26 09:26:22 [5] INFO  GuideEnricher.Service - Starting
2015-06-26 09:26:22 [7] INFO  GuideEnricher.Service - Connection and event listener task started...
2015-06-26 09:26:33 [10] INFO  GuideEnricher.Service - SubscribeServiceEvents() succeeded
2015-06-26 09:26:38 [12] DEBUG GuideEnricher.tvdb.TvdbLibAccess - Language: en
2015-06-26 09:26:38 [12] ERROR GuideEnricher.Service - Error enriching
System.AggregateException: One or more errors occurred. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: input
   at System.Text.RegularExpressions.Regex.IsMatch(String input)
   at GuideEnricher.Enricher.<AddUpcomingProgramsAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GuideEnricher.Enricher.<EnrichUpcomingProgramsAsync>d__8.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at GuideEnricher.Service.Enrich(Object state, ElapsedEventArgs eventArgs)
---> (Inner Exception #0) System.ArgumentNullException: Value cannot be null.
Parameter name: input
   at System.Text.RegularExpressions.Regex.IsMatch(String input)
   at GuideEnricher.Enricher.<AddUpcomingProgramsAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GuideEnricher.Enricher.<EnrichUpcomingProgramsAsync>d__8.MoveNext()<---

Config file:
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
    <section name="seriesMapping" type="GuideEnricher.Config.SeriesNameMapsSection, GuideEnricherService, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" allowDefinition="Everywhere" allowExeDefinition="MachineToApplication" restartOnExternalChanges="true"/>
    <section name="log4net" type="log4net.Config.Log4NetConfigurationSectionHandler, log4net"/>
    <section name="MatchMethodsSection" type="GuideEnricher.Config.MatchMethodsSection, GuideEnricherService"/>
  </configSections>
  
  <seriesMapping>
    
  </seriesMapping>
  <MatchMethodsSection>
    <MatchMethods>
      <add name="GuideEnricher.EpisodeMatchMethods.EpisodeTitleMatchMethod"/>
      <add name="GuideEnricher.EpisodeMatchMethods.NoPunctuationMatchMethod"/>
      <add name="GuideEnricher.EpisodeMatchMethods.RemoveCommonWordsMatchMethod"/>
      <add name="GuideEnricher.EpisodeMatchMethods.InQuotesInDescriptionMatchMethod"/>
      <add name="GuideEnricher.EpisodeMatchMethods.FirstSentenceInDescriptionMatchMethod"/>
      <add name="GuideEnricher.EpisodeMatchMethods.DescriptionStartsWithEpisodeTitleMatchMethod"/>
      <add name="GuideEnricher.EpisodeMatchMethods.SeasonAndEpisodeInDescriptionMatchMethod"/>
      <add name="GuideEnricher.EpisodeMatchMethods.NumericSeasonEpisodeMatchMethod"/>
      <add name="GuideEnricher.EpisodeMatchMethods.AirDateMatchMethod"/>
      <add name="GuideEnricher.EpisodeMatchMethods.AbsoluteEpisodeNumberMatchMethod" />
    </MatchMethods>
  </MatchMethodsSection>
  <log4net>
    <appender name="RollingLogFileAppender" type="log4net.Appender.RollingFileAppender">
      <file value="guideenricher.log"/>
      <appendToFile value="true"/>
      <maxSizeRollBackups value="10"/>
      <maximumFileSize value="5MB"/>
      <rollingStyle value="Size"/>
      <staticLogFileName value="true"/>
      <layout type="log4net.Layout.PatternLayout">
        <conversionPattern value="%date{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger - %message%newline"/>
      </layout>
    </appender>
    <appender name="Console" type="log4net.Appender.ConsoleAppender">
      <layout type="log4net.Layout.PatternLayout">
        <conversionPattern value="%message%newline"/>
      </layout>
    </appender>
    <root>
      <level value="DEBUG"/>
      <appender-ref ref="RollingLogFileAppender"/>
      <appender-ref ref="Console"/>
    </root>
    
  </log4net>
  <appSettings>
    
    <add key="TvDbLibCache" value="c:\\tvdblibcache\\"/>
    
    <add key="TvDbLanguage" value="en"/>
    
    <add key="serviceUrl" value="net.tcp://localhost:49830/GuideEnricher"/>
    
    <add key="sleepTimeInHours" value="12"/>

    
    <add key="maxShowNumberPerUpdate" value="20"/>

    
    <add key="ftrUrlHost" value="localhost"/>
    <add key="ftrUrlPort" value="49943"/>
    
    <add key="ftrUserName" value=""/>
    <add key="ftrUrlPassword" value=""/>
    
    <add key="dumpepisodes" value="false"/>
    
    <add key="updateAll" value="false"/>
    
    <add key="episodeInDescription" value="false"/>
    
    <add key="updateSubtitles" value="true"/>
  </appSettings>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5"/>
  </startup>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-2.6.8.0" newVersion="2.6.8.0"/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Threading.Tasks" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-2.6.8.0" newVersion="2.6.8.0"/>
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>

**Comment by aswede** [comment]
Chris - I sent the zip file to your email as I was not able to attach them to the post.

**Comment by ChrisRichner** [comment]
// skip already enriched entries
                    if (episodeDataValidRegEx.IsMatch(**guideProgram.EpisodeNumberDisplay**)) continue;

2015-06-26 11:36:26 [12] ERROR GuideEnricher.Service - Error enriching
System.AggregateException: One or more errors occurred. ---> **System.ArgumentNullException**: Value cannot be null.
Parameter name: input
   at System.Text.RegularExpressions.Regex.IsMatch(String input)
   at GuideEnricher.Enricher.<AddUpcomingProgramsAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GuideEnricher.Enricher.<EnrichUpcomingProgramsAsync>d__8.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at GuideEnricher.Service.Enrich(Object state, ElapsedEventArgs eventArgs)
---> (Inner Exception #0) System.ArgumentNullException: Value cannot be null.
Parameter name: input
   at System.Text.RegularExpressions.Regex.IsMatch(String input)
   at GuideEnricher.Enricher.<AddUpcomingProgramsAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GuideEnricher.Enricher.<EnrichUpcomingProgramsAsync>d__8.MoveNext()<---

**Comment by ChrisRichner** [comment]
Fix verified by @aswede
