### ISSUE TITLE
Timeout when failing to reach thetvdb.com

### ISSUE THREAD

**Issue by aswede** [ChrisRichner/ARGUS-TV-GuideEnhancer#7]
Not sure if this is the right place to leave this observation, but recently I have had repeated issues with GuideEnhancer where I lose all the season and episode information that has already been written to Argus. When I go into the log I always find an entry stating that:

Couldn't connect to Thetvdb.com to retrieve search results

the full message looks like:

TvdbLib.Exceptions.TvdbNotAvailableException: Couldn't connect to Thetvdb.com to retrieve search results for Lone Survivor, check your internet connection and the status of http://thetvdb.com
   at TvdbLib.TvdbDownloader.DownloadSearchResults(String _name, TvdbLanguage _language)
   at GuideEnricher.tvdb.TvDbService.SearchSeries(String name, TvdbLanguage language)
   at GuideEnricher.tvdb.TvdbLibAccess.getSeriesId(String seriesName)
   at GuideEnricher.Enricher.EnrichSeries(GuideEnricherSeries series)
   at GuideEnricher.Enricher.EnrichUpcomingPrograms()
   at GuideEnricher.Service.Enrich(Object state, ElapsedEventArgs eventArgs)

Doesa anyone have suggestions / thoughts?

**Comment by ChrisRichner** [comment]
The added code retries 3 times and waits 2 seconds between the retries.
